version: "3.9"
services:
  server:
    build: .
    restart: always
    ports:
    - 8080:8080
    depends_on: 
     - mysqldb
  mysqldb:
   image: "mysql:5.7"
   restart: always
   ports:
    - 3307:3307
   environment:
    MYSQL_DATABASE: constats
    MYSQL_USER: croff
    MYSQL_PASSWORD: croff
    MYSQL_ROOT_PASSWORD: croff